default: &default
  adapter: postgresql
  encoding: unicode

development:
  <<: *default
  database: webdata-dev
  username: postgres
  password: postgres

test:
  <<: *default
  database: webdata-test
  username: postgres
  password: postgres

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
